package cr.ac.una.prograiv.moviestar.domain;
// Generated 17/06/2016 04:31:10 PM by Hibernate Tools 4.3.1



/**
 * Catalogos generated by hbm2java
 */
public class Catalogos  implements java.io.Serializable {


     private Integer CId;
     private Categorias categorias;
     private Detalles detalles;
     private String CNombre;
     private String CDirector;
     private String CActorPrin;
     private Integer CCantidad;
     private String CTipo;
     private Float CPrecAlqu;
     private Float CPrecComp;
     private String CUrlImg;
     private String CDescrip;

    public Catalogos() {
    }

    public Catalogos(Categorias categorias, Detalles detalles, String CNombre, String CDirector, String CActorPrin, Integer CCantidad, String CTipo, Float CPrecAlqu, Float CPrecComp, String CUrlImg, String CDescrip) {
       this.categorias = categorias;
       this.detalles = detalles;
       this.CNombre = CNombre;
       this.CDirector = CDirector;
       this.CActorPrin = CActorPrin;
       this.CCantidad = CCantidad;
       this.CTipo = CTipo;
       this.CPrecAlqu = CPrecAlqu;
       this.CPrecComp = CPrecComp;
       this.CUrlImg = CUrlImg;
       this.CDescrip = CDescrip;
    }
   
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Detalles getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Detalles detalles) {
        this.detalles = detalles;
    }
    public String getCNombre() {
        return this.CNombre;
    }
    
    public void setCNombre(String CNombre) {
        this.CNombre = CNombre;
    }
    public String getCDirector() {
        return this.CDirector;
    }
    
    public void setCDirector(String CDirector) {
        this.CDirector = CDirector;
    }
    public String getCActorPrin() {
        return this.CActorPrin;
    }
    
    public void setCActorPrin(String CActorPrin) {
        this.CActorPrin = CActorPrin;
    }
    public Integer getCCantidad() {
        return this.CCantidad;
    }
    
    public void setCCantidad(Integer CCantidad) {
        this.CCantidad = CCantidad;
    }
    public String getCTipo() {
        return this.CTipo;
    }
    
    public void setCTipo(String CTipo) {
        this.CTipo = CTipo;
    }
    public Float getCPrecAlqu() {
        return this.CPrecAlqu;
    }
    
    public void setCPrecAlqu(Float CPrecAlqu) {
        this.CPrecAlqu = CPrecAlqu;
    }
    public Float getCPrecComp() {
        return this.CPrecComp;
    }
    
    public void setCPrecComp(Float CPrecComp) {
        this.CPrecComp = CPrecComp;
    }
    public String getCUrlImg() {
        return this.CUrlImg;
    }
    
    public void setCUrlImg(String CUrlImg) {
        this.CUrlImg = CUrlImg;
    }
    public String getCDescrip() {
        return this.CDescrip;
    }
    
    public void setCDescrip(String CDescrip) {
        this.CDescrip = CDescrip;
    }




}


