package cr.ac.una.prograiv.moviestar.domain;
// Generated 17/06/2016 04:31:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Detalles generated by hbm2java
 */
public class Detalles  implements java.io.Serializable {


     private Integer DId;
     private Ordenes ordenes;
     private String DTipo;
     private Date DFechaLimite;
     private Float DPrecio;
     private String DEstado;
     private int DCatalogo;
     private Set catalogoses = new HashSet(0);

    public Detalles() {
    }

	
    public Detalles(Ordenes ordenes, int DCatalogo) {
        this.ordenes = ordenes;
        this.DCatalogo = DCatalogo;
    }
    public Detalles(Ordenes ordenes, String DTipo, Date DFechaLimite, Float DPrecio, String DEstado, int DCatalogo, Set catalogoses) {
       this.ordenes = ordenes;
       this.DTipo = DTipo;
       this.DFechaLimite = DFechaLimite;
       this.DPrecio = DPrecio;
       this.DEstado = DEstado;
       this.DCatalogo = DCatalogo;
       this.catalogoses = catalogoses;
    }
   
    public Integer getDId() {
        return this.DId;
    }
    
    public void setDId(Integer DId) {
        this.DId = DId;
    }
    public Ordenes getOrdenes() {
        return this.ordenes;
    }
    
    public void setOrdenes(Ordenes ordenes) {
        this.ordenes = ordenes;
    }
    public String getDTipo() {
        return this.DTipo;
    }
    
    public void setDTipo(String DTipo) {
        this.DTipo = DTipo;
    }
    public Date getDFechaLimite() {
        return this.DFechaLimite;
    }
    
    public void setDFechaLimite(Date DFechaLimite) {
        this.DFechaLimite = DFechaLimite;
    }
    public Float getDPrecio() {
        return this.DPrecio;
    }
    
    public void setDPrecio(Float DPrecio) {
        this.DPrecio = DPrecio;
    }
    public String getDEstado() {
        return this.DEstado;
    }
    
    public void setDEstado(String DEstado) {
        this.DEstado = DEstado;
    }
    public int getDCatalogo() {
        return this.DCatalogo;
    }
    
    public void setDCatalogo(int DCatalogo) {
        this.DCatalogo = DCatalogo;
    }
    public Set getCatalogoses() {
        return this.catalogoses;
    }
    
    public void setCatalogoses(Set catalogoses) {
        this.catalogoses = catalogoses;
    }




}


